repos:
  - repo: local
    hooks:
      - id: run-command
        name: CommandRunner
        description: Use given command on all staged files one by one
        language: script
        stages: [pre-commit, manual]
        entry: ./hooks/run_command.sh
        args: [shellcheck,"-S","error"]
        types: [executable,shell]
